// Package captcha implements the login captcha and the adaptive risk-control
// guard for nmsappsrv.
//
// The captcha itself is a pure-digit image generated by mojocn/base64Captcha;
// the answer is stored server-side in Redis (key prefix captcha_code_, 10-min
// TTL) — mirroring the Java kaptcha scheme (GET /v2/captchaImage →
// {key, imageBase64}, answer in Redis).
//
// Unlike Java (which requires a captcha on every interactive login), Go uses an
// adaptive scheme: a captcha is only demanded after repeated failures. Three
// independent failure dimensions are tracked (username+IP, username, IP), each
// with a 10-minute sliding window. Crossing a dimension's threshold promotes it
// into a "captcha required" marker that also lives 10 minutes, so the challenge
// survives page refreshes. A successful login clears all counters and markers.
//
// Every Redis operation fails open: if Redis is unreachable the guard never
// blocks a login and never panics. This keeps the captcha a hardening layer,
// not a single point of failure.
package captcha

import (
	"context"
	"time"

	goredis "github.com/go-redis/redis/v8"
	"github.com/mojocn/base64Captcha"
)

const (
	captchaKeyPrefix = "captcha_code_"
	captchaTTL       = 10 * time.Minute

	failUIPPrefix = "login_fail_uip:"
	failUserPrefix = "login_fail_user:"
	failIPPrefix  = "login_fail_ip:"

	reqUIPPrefix = "captcha_req_uip:"
	reqUserPrefix = "captcha_req_user:"
	reqIPPrefix  = "captcha_req_ip:"

	failTTL = 10 * time.Minute
	reqTTL  = 10 * time.Minute

	// Thresholds: username+IP combo is the primary trigger (3); a username-wide
	// or IP-wide counter catches distributed attacks from many sources.
	thresholdUIP  = 3
	thresholdUser = 5
	thresholdIP   = 10

	defaultLength = 4
)

// Manager owns captcha generation/verification and the login risk-control
// guard. It is safe for concurrent use.
type Manager struct {
	captcha *base64Captcha.Captcha
	rdb     *goredis.Client
	length  int
}

// NewManager builds a captcha Manager backed by the given Redis client. length
// controls how many digits the captcha shows (Java's kaptchaLength); it falls
// back to defaultLength when <= 0.
func NewManager(rdb *goredis.Client, length int) *Manager {
	if length <= 0 {
		length = defaultLength
	}
	driver := base64Captcha.NewDriverDigit(40, 120, length, 0.4, 60)
	store := &redisStore{rdb: rdb, ttl: captchaTTL}
	return &Manager{
		captcha: base64Captcha.NewCaptcha(driver, store),
		rdb:     rdb,
		length:  length,
	}
}

// Generate produces a new captcha and returns its key (id) and the base64
// data-URI image string (already prefixed with "data:image/png;base64,"). The
// answer is stored server-side and must be supplied back via Verify.
func (m *Manager) Generate(ctx context.Context) (key, imageBase64 string, err error) {
	id, b64s, _, err := m.captcha.Generate()
	if err != nil {
		return "", "", err
	}
	return id, b64s, nil
}

// Verify checks the supplied answer against the stored captcha and consumes it
// (so a captcha can't be replayed).
func (m *Manager) Verify(ctx context.Context, key, answer string) bool {
	if key == "" || answer == "" {
		return false
	}
	return m.captcha.Verify(key, answer, true)
}

// ---------------------------------------------------------------------------
// Adaptive risk-control guard
// ---------------------------------------------------------------------------

// OnFailure records a failed login attempt for username+IP, updating the three
// independent failure counters and promoting any crossed threshold into a
// captcha-required marker (10-minute TTL each, dimensions independent).
func (m *Manager) OnFailure(username, ip string) {
	m.bump(failUIPPrefix+username+":"+ip, reqUIPPrefix+username+":"+ip, thresholdUIP)
	m.bump(failUserPrefix+username, reqUserPrefix+username, thresholdUser)
	m.bump(failIPPrefix+ip, reqIPPrefix+ip, thresholdIP)
}

// bump increments the failure counter for failKey (10-min TTL from first
// failure) and, once it reaches threshold, sets the corresponding reqKey
// marker. Redis errors are ignored (fail open).
func (m *Manager) bump(failKey, reqKey string, threshold int) {
	ctx := context.Background()
	n, err := m.rdb.Incr(ctx, failKey).Result()
	if err != nil {
		return
	}
	if n == 1 {
		_ = m.rdb.Expire(ctx, failKey, failTTL).Err()
	}
	if n >= int64(threshold) {
		_ = m.rdb.Set(ctx, reqKey, "1", reqTTL).Err()
	}
}

// OnSuccess clears all failure counters and captcha-required markers for the
// username+IP, so a successful login resets the risk state immediately.
func (m *Manager) OnSuccess(username, ip string) {
	ctx := context.Background()
	keys := []string{
		failUIPPrefix + username + ":" + ip,
		failUserPrefix + username,
		failIPPrefix + ip,
		reqUIPPrefix + username + ":" + ip,
		reqUserPrefix + username,
		reqIPPrefix + ip,
	}
	_ = m.rdb.Del(ctx, keys...).Err()
}

// IsRequired reports whether a captcha must be presented for this username+IP.
// Any of the three dimensions having a captcha-required marker triggers it.
// Returns false on Redis errors (fail open) so a Redis outage never blocks
// login.
func (m *Manager) IsRequired(username, ip string) bool {
	ctx := context.Background()
	keys := []string{
		reqUIPPrefix + username + ":" + ip,
		reqUserPrefix + username,
		reqIPPrefix + ip,
	}
	for _, k := range keys {
		n, err := m.rdb.Exists(ctx, k).Result()
		if err == nil && n > 0 {
			return true
		}
	}
	return false
}
