package corenet

// CoreNetworkData 对应 core_network_data 表 (74个Lob字段)
type CoreNetworkData struct {
	Id            int    `gorm:"primaryKey;autoIncrement" json:"id"`
	CoreNetworkId *int   `gorm:"column:core_network_id" json:"core_network_id"`
	ImsInfo                                  *string    `gorm:"column:{fn};type:longtext" json:"ims_info"`
	AmfInfo                                  *string    `gorm:"column:{fn};type:longtext" json:"amf_info"`
	AusfInfo                                 *string    `gorm:"column:{fn};type:longtext" json:"ausf_info"`
	UdmInfo                                  *string    `gorm:"column:{fn};type:longtext" json:"udm_info"`
	SmfInfo                                  *string    `gorm:"column:{fn};type:longtext" json:"smf_info"`
	PcfInfo                                  *string    `gorm:"column:{fn};type:longtext" json:"pcf_info"`
	UpfInfo                                  *string    `gorm:"column:{fn};type:longtext" json:"upf_info"`
	UdmAlarm                                 *string    `gorm:"column:{fn};type:longtext" json:"udm_alarm"`
	SmfAlarm                                 *string    `gorm:"column:{fn};type:longtext" json:"smf_alarm"`
	ImsUeNumber                              *string    `gorm:"column:{fn};type:longtext" json:"ims_ue_number"`
	ImsUeInfo                                *string    `gorm:"column:{fn};type:longtext" json:"ims_ue_info"`
	SmfUeNumber                              *string    `gorm:"column:{fn};type:longtext" json:"smf_ue_number"`
	SmfUeInfo                                *string    `gorm:"column:{fn};type:longtext" json:"smf_ue_info"`
	AmfBaseStationInfo                       *string    `gorm:"column:{fn};type:longtext" json:"amf_base_station_info"`
	PcfUeInfo                                *string    `gorm:"column:{fn};type:longtext" json:"pcf_ue_info"`
	ConfigImsSystem                          *string    `gorm:"column:{fn};type:longtext" json:"config_ims_system"`
	ConfigImsPlmn                            *string    `gorm:"column:{fn};type:longtext" json:"config_ims_plmn"`
	ConfigImsMmtelDialplan                   *string    `gorm:"column:{fn};type:longtext" json:"config_ims_mmtel_dialplan"`
	ConfigImsDsSystem                        *string    `gorm:"column:{fn};type:longtext" json:"config_ims_ds_system"`
	ConfigAmfSystem                          *string    `gorm:"column:{fn};type:longtext" json:"config_amf_system"`
	ConfigAmfAssociation                     *string    `gorm:"column:{fn};type:longtext" json:"config_amf_association"`
	ConfigAmfGuami                           *string    `gorm:"column:{fn};type:longtext" json:"config_amf_guami"`
	ConfigAmfTai                             *string    `gorm:"column:{fn};type:longtext" json:"config_amf_tai"`
	ConfigAmfSlice                           *string    `gorm:"column:{fn};type:longtext" json:"config_amf_slice"`
	ConfigAusfSystem                         *string    `gorm:"column:{fn};type:longtext" json:"config_ausf_system"`
	ConfigUdmSystem                          *string    `gorm:"column:{fn};type:longtext" json:"config_udm_system"`
	ConfigUdmSubsUeAmbr                      *string    `gorm:"column:{fn};type:longtext" json:"config_udm_subs_ue_ambr"`
	ConfigUdmSubsNssais                      *string    `gorm:"column:{fn};type:longtext" json:"config_udm_subs_nssais"`
	ConfigUdmForbiddenAreas                  *string    `gorm:"column:{fn};type:longtext" json:"config_udm_forbidden_areas"`
	ConfigUdmServiceAreaRestriction          *string    `gorm:"column:{fn};type:longtext" json:"config_udm_service_area_restriction"`
	ConfigUdmSmfSelection                    *string    `gorm:"column:{fn};type:longtext" json:"config_udm_smf_selection"`
	ConfigUdmDnn                             *string    `gorm:"column:{fn};type:longtext" json:"config_udm_dnn"`
	ConfigUdmEpsTemplate                     *string    `gorm:"column:{fn};type:longtext" json:"config_udm_eps_template"`
	ConfigUdmEpsApn                          *string    `gorm:"column:{fn};type:longtext" json:"config_udm_eps_apn"`
	ConfigUdmApplicationServer               *string    `gorm:"column:{fn};type:longtext" json:"config_udm_application_server"`
	ConfigUdmScscfSet                        *string    `gorm:"column:{fn};type:longtext" json:"config_udm_scscf_set"`
	ConfigUdmTriggerPoint                    *string    `gorm:"column:{fn};type:longtext" json:"config_udm_trigger_point"`
	ConfigUdmS6aServer                       *string    `gorm:"column:{fn};type:longtext" json:"config_udm_s6a_server"`
	ConfigUdmCxServer                        *string    `gorm:"column:{fn};type:longtext" json:"config_udm_cx_server"`
	ConfigUpfGeneral                         *string    `gorm:"column:{fn};type:longtext" json:"config_upf_general"`
	ConfigUpfLogger                          *string    `gorm:"column:{fn};type:longtext" json:"config_upf_logger"`
	ConfigUpfPfcp                            *string    `gorm:"column:{fn};type:longtext" json:"config_upf_pfcp"`
	ConfigUpfTelnet                          *string    `gorm:"column:{fn};type:longtext" json:"config_upf_telnet"`
	ConfigUpfRedisDb                         *string    `gorm:"column:{fn};type:longtext" json:"config_upf_redis_db"`
	ConfigUpfDataForwarderCommon             *string    `gorm:"column:{fn};type:longtext" json:"config_upf_data_forwarder_common"`
	ConfigUpfDataForwarderUpfd               *string    `gorm:"column:{fn};type:longtext" json:"config_upf_data_forwarder_upfd"`
	ConfigUpfDataInterfaceList               *string    `gorm:"column:{fn};type:longtext" json:"config_upf_data_interface_list"`
	ConfigUpfNetworkControlCommon            *string    `gorm:"column:{fn};type:longtext" json:"config_upf_network_control_common"`
	ConfigUpfNetworkControlDnnList           *string    `gorm:"column:{fn};type:longtext" json:"config_upf_network_control_dnn_list"`
	ConfigUpfNetworkControlSnssaiList        *string    `gorm:"column:{fn};type:longtext" json:"config_upf_network_control_snssai_list"`
	ConfigUpfNetworkControlAclWhiteList      *string    `gorm:"column:{fn};type:longtext" json:"config_upf_network_control_acl_white_list"`
	ConfigUpfNetworkControlAclBlackList      *string    `gorm:"column:{fn};type:longtext" json:"config_upf_network_control_acl_black_list"`
	ConfigUpfNetworkControlDnsServerList     *string    `gorm:"column:{fn};type:longtext" json:"config_upf_network_control_dns_server_list"`
	ConfigUpfDpiCommon                       *string    `gorm:"column:{fn};type:longtext" json:"config_upf_dpi_common"`
	ConfigUpfDpiHeaderEnrichInfoList         *string    `gorm:"column:{fn};type:longtext" json:"config_upf_dpi_header_enrich_info_list"`
	ConfigUpfDpiAppList                      *string    `gorm:"column:{fn};type:longtext" json:"config_upf_dpi_app_list"`
	ConfigPcfSystem                          *string    `gorm:"column:{fn};type:longtext" json:"config_pcf_system"`
	ConfigPcfServiceAreaRestriction          *string    `gorm:"column:{fn};type:longtext" json:"config_pcf_service_area_restriction"`
	ConfigPcfPccRules                        *string    `gorm:"column:{fn};type:longtext" json:"config_pcf_pcc_rules"`
	ConfigPcfSessionRules                    *string    `gorm:"column:{fn};type:longtext" json:"config_pcf_session_rules"`
	ConfigPcfGxServer                        *string    `gorm:"column:{fn};type:longtext" json:"config_pcf_gx_server"`
	ConfigPcfRxServer                        *string    `gorm:"column:{fn};type:longtext" json:"config_pcf_rx_server"`
	ConfigPcfFlowTemplate                    *string    `gorm:"column:{fn};type:longtext" json:"config_pcf_flow_template"`
	ConfigPcfQosTemplate                     *string    `gorm:"column:{fn};type:longtext" json:"config_pcf_qos_template"`
	ConfigPcfUsageMonitoringTemplate         *string    `gorm:"column:{fn};type:longtext" json:"config_pcf_usage_monitoring_template"`
	ConfigPcfTrafficControlTemplate          *string    `gorm:"column:{fn};type:longtext" json:"config_pcf_traffic_control_template"`
	ConfigPcfHeaderEnrichTemplate            *string    `gorm:"column:{fn};type:longtext" json:"config_pcf_header_enrich_template"`
	ConfigSmfSmfSystem                       *string    `gorm:"column:{fn};type:longtext" json:"config_smf_smf_system"`
	ConfigSmfSpgwSystem                      *string    `gorm:"column:{fn};type:longtext" json:"config_smf_spgw_system"`
	ConfigSmfupfConfig                       *string    `gorm:"column:{fn};type:longtext" json:"config_smfupf_config"`
	ConfigSmfDnnSelectUpf                    *string    `gorm:"column:{fn};type:longtext" json:"config_smf_dnn_select_upf"`
	ConfigSmfDnnTaiSelectUpf                 *string    `gorm:"column:{fn};type:longtext" json:"config_smf_dnn_tai_select_upf"`
	ConfigSmfSnssaiSelectUpf                 *string    `gorm:"column:{fn};type:longtext" json:"config_smf_snssai_select_upf"`
	ConfigSmfOfflineChargingConfig           *string    `gorm:"column:{fn};type:longtext" json:"config_smf_offline_charging_config"`
	UeInfos                                  *string    `gorm:"column:{fn};type:longtext" json:"ue_infos"`
}

func (CoreNetworkData) TableName() string { return "core_network_data" }
