package security

import (
	"context"
	"fmt"
	"time"

	"nmsappsrv/pkg/redis"

	"gorm.io/gorm"
)

// SaltHolder mirrors the Java SaltHolder component contract:
//
//	getSalt(userId) -> salt string or ""
//	saveSalt(salt, userId) -> error
//
// The Java implementation (core/component/SaltHolder.java) stores each
// user's salt in HashiCorp Vault at path
//
//	/cubbyhole/nms/profile/{userId}   key = "salt"
//
// and during CoreRunner startup migrates any lingering values from the
// sys_user.salt DB column into Vault, clearing the DB column afterwards.
//
// For environments where Vault is not yet available this Go holder falls
// back to a Redis cache with the same logical key layout, then to the DB
// column. A production deployment should replace the implementation with
// a real Vault client; the fallback chain preserves compatibility with
// existing rows generated by the Java server on shared infrastructure.
type SaltHolder interface {
	GetSalt(userId int) (string, error)
	SaveSalt(salt string, userId int) error
}

// vault path constants — identical to SaltHolder.java lines 22 and 39.
const (
	vaultPathPrefix   = "/cubbyhole/nms/profile/"
	vaultSaltDataKey  = "salt"
	redisSaltKeyFmt   = "salt:profile:%d" // fallback cache
	redisSaltTTL      = 24 * time.Hour
)

// ---------------------------------------------------------------------------
// Fallback SaltHolder — Redis + DB column (no Vault dependency required)
// ---------------------------------------------------------------------------

// RedisDBBackedSaltHolder is the default implementation. Lookup order:
//  1. Redis key `salt:profile:{userId}` (fast path)
//  2. MySQL `sys_user.salt` column (Java startup-migration source-of-truth)
//  3. Save back to Redis for subsequent lookups
type RedisDBBackedSaltHolder struct {
	db *gorm.DB
}

func NewRedisDBBackedSaltHolder(db *gorm.DB) SaltHolder {
	return &RedisDBBackedSaltHolder{db: db}
}

type sysUserSaltRow struct {
	Id   int     `gorm:"column:id;primaryKey"`
	Salt *string `gorm:"column:salt"`
}

func (sysUserSaltRow) TableName() string { return "sys_user" }

func (h *RedisDBBackedSaltHolder) GetSalt(userId int) (string, error) {
	if userId <= 0 {
		return "", nil
	}
	ctx := context.Background()

	// 1) Redis fast path
	rkey := fmt.Sprintf(redisSaltKeyFmt, userId)
	if v, err := redis.Get(ctx, rkey); err == nil && v != "" {
		return v, nil
	}

	// 2) DB fallback (Java's pre-migration source-of-truth)
	var row sysUserSaltRow
	if err := h.db.Table("sys_user").Select("id, salt").Where("id = ?", userId).First(&row).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return "", nil
		}
		return "", fmt.Errorf("salt holder: db lookup: %w", err)
	}
	salt := ""
	if row.Salt != nil {
		salt = *row.Salt
	}

	// 3) Cache for next time
	if salt != "" {
		_ = redis.Set(ctx, rkey, salt, redisSaltTTL)
	}
	return salt, nil
}

func (h *RedisDBBackedSaltHolder) SaveSalt(salt string, userId int) error {
	if userId <= 0 {
		return nil
	}
	ctx := context.Background()

	// Write DB column AND Redis. The Java server writes to Vault only,
	// but since we can't rely on Vault presence we mirror to both, so a
	// future Java instance that does the CoreRunner vault-migration loop
	// will find the value in sys_user.salt and migrate it transparently.
	if err := h.db.Table("sys_user").Where("id = ?", userId).Update("salt", salt).Error; err != nil {
		return fmt.Errorf("salt holder: db save: %w", err)
	}
	rkey := fmt.Sprintf(redisSaltKeyFmt, userId)
	return redis.Set(ctx, rkey, salt, redisSaltTTL)
}

// GenerateSalt produces a random 16-byte hex salt (32 hex chars) — matches
// the entropy of typical Java per-user salts. The caller is responsible for
// persisting the generated value via SaltHolder.SaveSalt before hashing.
func GenerateSalt() string {
	buf := make([]byte, 16)
	if _, err := cryptoRandRead(buf); err != nil {
		// Math/rand fallback; this is not ideal but preserves forward progress.
		for i := range buf {
			buf[i] = byte(pseudoRandIntn(256))
		}
	}
	return fmt.Sprintf("%x", buf)
}
