ausf:
  system:
    display: "System"
    list:
    - name: "serviceIP"
      type: "ipv4"
      value: "172.16.5.130"
      access: "read-write"
      filter: ''
      display: "Service IP"
      comment: ""
    - name: "servicePort"
      type: "int"
      value: "8080"
      access: "read-write"
      filter: "0~65535"
      display: "Service Port"
      comment: ""
    - name: "scheme"
      type: "enum"
      value: "http"
      access: "read-write"
      filter: "{\"0\":\"HTTP\", \"1\":\"HTTPS\"}"
      display: "Scheme"
      comment: ""
    - name: "nrfUri"
      type: "string"
      value: "http://172.16.5.180:8080"
      access: "read-write"
      filter: ''
      display: "NRF URI"
      comment: ""
    - name: "udmUri"
      type: "string"
      value: "http://172.16.5.140:8080"
      access: "read-write"
      filter: ''
      display: "UDM URI"
      comment: ""
    - name: "groupId"
      type: "string"
      value: "0"
      access: "read-write"
      filter: ''
      display: "Group ID"
      comment: ""
