ims:
  system:
    display: "System"
    list:
      - name: "label"
        type: "string"
        value: "ims-core"
        access: "read-write"
        filter: ""
        display: "Label"
        comment: ""
      - name: "hplmnMCC"
        type: "string"
        value: "001"
        access: "read-only"
        filter: ""
        display: "HPLMN MCC"
        comment: ""
      - name: "hplmnMNC"
        type: "string"
        value: "01"
        access: "read-only"
        filter: ""
        display: "HPLMN MNC"
        comment: ""
      - name: "LocalNetworkIPv4"
        type: "ipv4"
        value: "172.16.5.110"
        access: "read-write"
        filter: ""
        display: "Local Network IPv4"
        comment: ""
      - name: "serviceIP"
        type: "ipv4"
        value: "172.16.5.110"
        access: "read-write"
        filter: ""
        display: "Public Network IPv4"
        comment: ""
      - name: "serviceIPv6"
        type: "ipv6"
        value: ""
        access: "read-write"
        filter: ""
        display: "Public Network IPv6"
        comment: ""
      - name: "domainName1"
        type: "string"
        value: "ims.mnc001.mcc001.3gppnetwork.org"
        access: "read-only"
        filter: ""
        display: "Domain Name 1"
        comment: ""
      - name: "domainName2"
        type: "string"
        value: ""
        access: "read-only"
        filter: ""
        display: "Domain Name 2"
        comment: ""
      - name: "domainName3"
        type: "string"
        value: ""
        access: "read-only"
        filter: ""
        display: "Domain Name 3"
        comment: ""
      - name: "domainName4"
        type: "string"
        value: ""
        access: "read-only"
        filter: ""
        display: "Domain Name 4"
        comment: ""
      - name: "multiIPStackInd"
        type: "bool"
        value: "false"
        access: "read-write"
        filter: '{"0":"false", "1":"true"}'
        display: "MultiIPStack Indicator"
        comment: ""
      - name: "registerTimer"
        type: "int"
        value: "7200"
        access: "read-write"
        filter: "120~1000000"
        display: "Register Timer"
        comment: ""
      - name: "maxCallDuration"
        type: "int"
        value: "43200"
        access: "read-write"
        filter: "1800~1000000"
        display: "Max Call Duration"
        comment: ""
      - name: "internalSMSInd"
        type: "bool"
        value: "false"
        access: "read-write"
        filter: '{"0":"false", "1":"true"}'
        display: "Internal SMS Indicator"
        comment: ""
      - name: "internalCDRInd"
        type: "bool"
        value: "false"
        access: "read-write"
        filter: '{"0":"false", "1":"true"}'
        display: "Internal CDR Indicator"
        comment: ""
      - name: "internalKPIInd"
        type: "bool"
        value: "false"
        access: "read-write"
        filter: '{"0":"false", "1":"true"}'
        display: "Internal KPI Indicator"
        comment: ""
      - name: "pcfIP"
        type: "ipv4"
        value: "172.16.5.160"
        access: "read-write"
        filter: ""
        display: "PCF IP Address"
        comment: ""
  plmn:
    display: "PLMN List"
    array:
      - name: "index"
        type: "int"
        value: "0"
        access: "read-only"
        filter: "0~15"
        display: "Index"
        comment: "0~15"
      - name: "mcc"
        type: "regex"
        value: "001"
        access: "read-write"
        filter: "^[0-9]{3}$"
        display: "MCC"
        comment: ""
      - name: "mnc"
        type: "regex"
        value: "01"
        access: "read-write"
        filter: "^[0-9]{2,3}$"
        display: "MNC"
        comment: ""
      - name: "domain"
        type: "string"
        value: "ims.mnc001.mcc001.3gppnetwork.org"
        access: "read-only"
        filter: "0~128"
        display: "Domain"
        comment: ""
  mmtel_dialplan:
    display: "MMTEL Dialplan"
    array:
      - name: "index"
        type: "int"
        value: "0"
        access: "read-only"
        filter: "0~15"
        display: "Index"
        comment: "0~15"
      - name: "naName"
        type: "string"
        value: ""
        access: "read-only"
        filter: "0~128"
        display: "NaName"
        comment: ""
      - name: "title"
        type: "string"
        value: ""
        access: "read-write"
        filter: "0~128"
        display: "Title"
        comment: ""
      - name: "method"
        type: "string"
        value: "0"
        access: "read-write"
        filter: "0-2"
        display: "Method"
        comment: ""
      - name: "prefix"
        type: "string"
        value: ""
        access: "read-write"
        filter: "0~128"
        display: "Prefix"
        comment: ""
      - name: "start"
        type: "string"
        value: ""
        access: "read-write"
        filter: "0~128"
        display: "Start"
        comment: ""
      - name: "end"
        type: "string"
        value: ""
        access: "read-write"
        filter: "0~128"
        display: "End"
        comment: ""
      - name: "attrib"
        type: "string"
        value: ""
        access: "read-write"
        filter: "0~128"
        display: "Attrib"
        comment: ""
      - name: "numberLen"
        type: "string"
        value: ""
        access: "read-write"
        filter: "0~128"
        display: "Number Len"
        comment: ""
      - name: "rsc"
        type: "string"
        value: ""
        access: "read-write"
        filter: "0~128"
        display: "Rsc"
        comment: ""
      - name: "e164Nai"
        type: "string"
        value: ""
        access: "read-write"
        filter: "0~128"
        display: "E164 Nai"
        comment: ""
      - name: "e164Delete"
        type: "string"
        value: ""
        access: "read-write"
        filter: "0~128"
        display: "E164 Delete"
        comment: ""
      - name: "e164Insert"
        type: "string"
        value: ""
        access: "read-write"
        filter: "0~128"
        display: "E164 Insert"
        comment: ""
      - name: "adminState"
        type: "enum"
        value: "0"
        access: "read-write"
        filter: '{"0":"Close", "1":"Open"}'
        display: "Admin State"
        comment: "Enable: Close/Open"
  ds_system:
    display: "DS System"
    list:
      - name: "dispatchSystemInd"
        type: "bool"
        value: "false"
        access: "read-write"
        filter: '{"0":"false", "1":"true"}'
        display: "Dispatch System Indicator"
        comment: ""
      - name: "transcodeInd"
        type: "bool"
        value: "false"
        access: "read-write"
        filter: '{"0":"false", "1":"true"}'
        display: "Transcode Indicator"
        comment: ""
      - name: "dispatchSystemIP"
        type: "ipv4"
        value: "1.0.0.1"
        access: "read-write"
        filter: ""
        display: "Dispatch System IPv4"
        comment: ""
      - name: "dispatchSystemPort"
        type: "int"
        value: "5060"
        access: "read-write"
        filter: ""
        display: "Dispatch System Port"
        comment: ""
