mme:
  system:
    display: "System Config"
    list:
      - name: "csfbEnabled"
        type: "bool"
        value: "false"
        access: "read-write"
        filter: '{"0":"false","1":"true"}'
        display: "CSFB Enabled"
        comment: "true|false"
      - name: "volteEnabled"
        type: "bool"
        value: "false"
        access: "read-write"
        filter: '{"0":"false","1":"true"}'
        display: "VoLTE Enabled"
        comment: "true|false"
      - name: "s1MmeIp"
        type: "string"
        value: "192.168.1.179"
        access: "read-write"
        filter: "0~64"
        display: "S1 MME IP"
        comment: "0~64"
      - name: "s1MmePort"
        type: "int"
        value: "36412"
        access: "read-only"
        filter: "0~65535"
        display: "S1 MME Port"
        comment: "0~65535"
      - name: "s11MmeIp"
        type: "string"
        value: "192.168.1.179"
        access: "read-write"
        filter: "0~64"
        display: "S11 MME IP"
        comment: "0~64"
      - name: "s11MmePort"
        type: "int"
        value: "2123"
        access: "read-write"
        filter: "0~65535"
        display: "S11 MME Port"
        comment: "0~65535"
      - name: "s10MmeIp"
        type: "string"
        value: "192.168.1.178"
        access: "read-write"
        filter: "0~64"
        display: "S10 MME IP"
        comment: "0~64"
      - name: "s10MmePort"
        type: "int"
        value: "2123"
        access: "read-write"
        filter: "0~65535"
        display: "S10 MME Port"
        comment: "0~65535"
      - name: "sgsMmeIp"
        type: "string"
        value: "192.168.1.179"
        access: "read-write"
        filter: "0~64"
        display: "SGs MME IP"
        comment: "0~64"
      - name: "sgsMmePort"
        type: "int"
        value: "29118"
        access: "read-only"
        filter: "0~65535"
        display: "SGs MME Port"
        comment: "0~65535"
      - name: "s6aIdentity"
        type: "string"
        value: "mme.epc.mnc001.mcc001.3gppnetwork.org"
        access: "read-write"
        filter: "0~100"
        display: "S6A MME Identity"
        comment: "0~100"
      - name: "localIp"
        type: "string"
        value: "172.16.5.220"
        access: "read-write"
        filter: "0~20"
        display: "S6A MME IP"
        comment: "0~20"
  gummei:
    display: "Gummei List"
    array:
      - name: "index"
        type: "int"
        value: "0"
        access: "read"
        filter: "0~15"
        display: "Index"
        comment: "0~15"
      - name: "plmnId"
        type: "regex"
        value: "00101"
        access: "read-write"
        filter: "^[0-9]{5,6}$"
        display: "PLMN ID"
        comment: "^[0-9]{5,6}$"
      - name: "groupId"
        type: "int"
        value: "4"
        access: "read-write"
        filter: "0~65535"
        display: "Group ID"
        comment: "0~65535"
      - name: "code"
        type: "int"
        value: "1"
        access: "read-write"
        filter: "0~255"
        display: "Code"
        comment: "0~255"
  tai:
    display: "TAI List"
    array:
      - name: "index"
        type: "int"
        value: "0"
        access: "read"
        filter: "0~15"
        display: "Index"
        comment: "0~15"
      - name: "plmnId"
        type: "regex"
        value: "00101"
        access: "read-write"
        filter: "^[0-9]{5,6}$"
        display: "PLMN ID"
        comment: "^[0-9]{5,6}$"
      - name: "tac"
        type: "int"
        value: "1"
        access: "read-write"
        filter: "0~65535"
        display: "TAC"
        comment: "0~65535"
  hss:
    display: "HSS List"
    array:
      - name: "index"
        type: "int"
        value: "0"
        access: "read"
        filter: "0~15"
        display: "Index"
        comment: "0~15"
      - name: "imsiPre"
        type: "regex"
        value: "00101"
        access: "read-write"
        filter: "^[0-9]{1,15}$"
        display: "IMSI Prefix"
        comment: "^[0-9]{1,15}$"
      - name: "hssHostname"
        type: "string"
        value: "hss.ims.mnc001.mcc001.3gppnetwork.org"
        access: "read-write"
        filter: "0~128"
        display: "HSS Hostname"
        comment: "0~128"
      - name: "protocol"
        type: "string"
        value: "SCTP"
        access: "read-write"
        filter: "0~8"
        display: "Protocol"
        comment: "SCTP|TCP"
      - name: "hssPort"
        type: "int"
        value: "3868"
        access: "read-write"
        filter: "0~65535"
        display: "HSS Port"
        comment: "0~65535"
  sgw:
    display: "SGW List"
    array:
      - name: "index"
        type: "int"
        value: "0"
        access: "read"
        filter: "0~15"
        display: "Index"
        comment: "0~15"
      - name: "plmnId"
        type: "regex"
        value: "00101"
        access: "read-write"
        filter: "^[0-9]{5,6}$"
        display: "PLMN ID"
        comment: "^[0-9]{5,6}$"
      - name: "tac"
        type: "int"
        value: "1"
        access: "read-write"
        filter: "0~65535"
        display: "TAC"
        comment: "0~65535"
      - name: "sgwIp"
        type: "string"
        value: "172.16.5.150"
        access: "read-write"
        filter: "0~64"
        display: "SGW IP"
        comment: "0~64"
  pgw:
    display: "PGW List"
    array:
      - name: "index"
        type: "int"
        value: "0"
        access: "read"
        filter: "0~15"
        display: "Index"
        comment: "0~15"
      - name: "plmnId"
        type: "regex"
        value: "00101"
        access: "read-write"
        filter: "^[0-9]{5,6}$"
        display: "PLMN ID"
        comment: "^[0-9]{5,6}$"
      - name: "apn"
        type: "string"
        value: "internet"
        access: "read-write"
        filter: "0~128"
        display: "APN"
        comment: "0~128"
      - name: "pgwIp"
        type: "string"
        value: "192.168.1.181"
        access: "read-write"
        filter: "0~64"
        display: "PGW IP"
        comment: "0~64"
  amf:
    display: "AMF List"
    array:
      - name: "index"
        type: "int"
        value: "0"
        access: "read"
        filter: "0~15"
        display: "Index"
        comment: "0~15"
      - name: "plmnId"
        type: "regex"
        value: "00101"
        access: "read-write"
        filter: "^[0-9]{5,6}$"
        display: "PLMN ID"
        comment: "^[0-9]{5,6}$"
      - name: "tac"
        type: "int"
        value: "1"
        access: "read-write"
        filter: "0~16777215"
        display: "TAC"
        comment: "0~16777215"
      - name: "regionId"
        type: "int"
        value: "1"
        access: "read-write"
        filter: "0~255"
        display: "Region ID"
        comment: "0~255"
      - name: "setId"
        type: "int"
        value: "1"
        access: "read-write"
        filter: "0~1023"
        display: "Set ID"
        comment: "0~1023"
      - name: "pointer"
        type: "int"
        value: "1"
        access: "read-write"
        filter: "0~63"
        display: "Pointer"
        comment: "0~63"
      - name: "amfIp"
        type: "string"
        value: "172.16.5.120"
        access: "read-write"
        filter: "0~64"
        display: "AMF IP"
        comment: "0~64"
