mocngw:
  system:
    display: "System Config"
    list:
    - name: "s1apSouthAddr"
      type: "string"
      value: "192.168.7.163"
      access: "read-write"
      filter: '0~64'
      display: "S1AP South Address"
      comment: ""
    - name: "s1apNorthAddr"
      type: "string"
      value: "192.168.8.163"
      access: "read-write"
      filter: '0~64'
      display: "S1AP North Address"
      comment: ""
    - name: "tac"
      type: "int"
      value: "1"
      access: "read-write"
      filter: '0~65535'
      display: "TAC"
      comment: "0~65535"
    - name: "enbId"
      type: "int"
      value: "24"
      access: "read-write"
      filter: "0~1048575"
      display: "ENB ID"
      comment: "0~1048575"
    - name: "userPlaneEnabled"
      type: "bool"
      value: "0"
      access: "read-write"
      filter: '{"0":"false","1":"true"}'
      display: "User Plane Enabled"
      comment: ""
    - name: "pfcpAddr"
      type: "string"
      value: "192.168.7.163"
      access: "read-write"
      filter: '0~64'
      display: "PFCP Address"
      comment: ""
  mme:
    display: "MME List"
    array:
    - name: "index"
      type: "int"
      value: "0"
      access: "read-only"
      filter: '0~15'
      display: "Index"
      comment: "0~15"
    - name: "s1apAddr"
      type: "string"
      value: "192.168.1.161"
      access: "read-write"
      filter: '0~64'
      display: "S1AP Address"
      comment: ""
    - name: "s1apPort"
      type: "int"
      value: "36412"
      access: "read-write"
      filter: "0~65535"
      display: "S1AP Port"
      comment: "0~65535"
    - name: "plmnId"
      type: "regex"
      value: '00101'
      access: "read-write"
      filter: '^[0-9]{5,6}$'
      display: "PLMN ID"
      comment: ""
  upgw:
    display: "UPGW Config"
    list:
    - name: "pfcpAddr"
      type: "string"
      value: "192.168.1.159"
      access: "read-write"
      filter: '0~64'
      display: "PFCP Address"
      comment: ""
    - name: "pfcpPort"
      type: "int"
      value: "8805"
      access: "read-write"
      filter: "0~65535"
      display: "PFCP Port"
      comment: "0~65535"
    - name: "gtpuSouthAddr"
      type: "string"
      value: "10.10.1.2"
      access: "read-write"
      filter: '0~64'
      display: "GTP-U South Address"
      comment: ""
    - name: "gtpuNorthAddr"
      type: "string"
      value: "192.168.7.123"
      access: "read-write"
      filter: '0~64'
      display: "GTP-U North Address"
      comment: ""
