nssf:
  general:
    display: "General"
    list:
    - name: "nssfName"
      type: "string"
      value: ""
      access: "read-write"
      filter: ''
      display: "NSSF Name"
      comment: ""
    - name: "nrfUri"
      type: "string"
      value: ""
      access: "read-write"
      filter: ''
      display: "NRF URI"
      comment: ""
    - name: "logLevel"
      type: "string"
      value: "error"
      access: "read-write"
      filter: ''
      display: "Log Level"
      comment: ""
    - name: "nfId"
      type: "string"
      value: ""
      access: "read-write"
      filter: ''
      display: "NF ID"
      comment: ""
    - name: "systemId"
      type: "int"
      value: "0"
      access: "read-write"
      filter: ''
      display: "System ID"
      comment: ""
  sbi:
    display: "SBI"
    list:
      - name: "scheme"
        type: "string"
        value: "http"
        access: "read-write"
        filter: ''
        display: "Scheme"
        comment: ""
      - name: "registerIpv4"
        type: "string"
        value: ""
        access: "read-write"
        filter: ''
        display: "Register IPv4"
        comment: ""
      - name: "bindingIpv4"
        type: "string"
        value: ""
        access: "read-write"
        filter: ''
        display: "Binding IPv4"
        comment: ""
      - name: "registerIpv6"
        type: "string"
        value: ""
        access: "read-write"
        filter: ''
        display: "Register IPv6"
        comment: ""
      - name: "bindingIpv6"
        type: "string"
        value: ""
        access: "read-write"
        filter: ''
        display: "Binding IPv6"
        comment: ""
      - name: "ipType"
        type: "string"
        value: "ipv4"
        access: "read-write"
        filter: ''
        display: "IP Type"
        comment: ""
      - name: "port"
        type: "int"
        value: "8080"
        access: "read-write"
        filter: ''
        display: "Port"
        comment: ""
      - name: "telnetIpv4"
        type: "string"
        value: ""
        access: "read-write"
        filter: ''
        display: "Telnet IPv4"
        comment: ""
      - name: "telnetIpv6"
        type: "string"
        value: ""
        access: "read-write"
        filter: ''
        display: "Telnet IPv6"
        comment: ""
      - name: "telnetPort"
        type: "int"
        value: "4100"
        access: "read-write"
        filter: ''
        display: "Telnet Port"
        comment: ""
  supportedNetworkSliceList:
    display: "Supported Network Slice List"
    array:
      - name: "index"
        type: "int"
        value: "1"
        access: "read-only"
        filter: '1~32'
        display: "Index"
        comment: "1~32"
      - name: "mcc"
        type: "string"
        value: "001"
        access: "read-write"
        filter: ''
        display: "MCC"
        comment: ""
      - name: "mnc"
        type: "string"
        value: "01"
        access: "read-write"
        filter: ''
        display: "MNC"
        comment: ""
      - name: "tac"
        type: "string"
        value: ""
        access: "read-write"
        filter: ''
        display: "TAC"
        comment: ""
      - name: "supportedSst"
        type: "int"
        value: ""
        access: "read-write"
        filter: ''
        display: "Supported SST"
        comment: ""
      - name: "supportedSd"
        type: "string"
        value: ""
        access: "read-write"
        filter: ''
        display: "Supported SD"
        comment: ""
      - name: "restrictedSst"
        type: "int"
        value: ""
        access: "read-write"
        filter: ''
        display: "Restricted SST"
        comment: ""
      - name: "restrictedSd"
        type: "string"
        value: ""
        access: "read-write"
        filter: ''
        display: "Restricted SD"
        comment: ""
      - name: "nrfId"
        type: "string"
        value: ""
        access: "read-write"
        filter: ''
        display: "NRF ID"
        comment: ""
      - name: "nsiId"
        type: "string"
        value: ""
        access: "read-write"
        filter: ''
        display: "NSI ID"
        comment: ""
      - name: "accessType"
        type: "string"
        value: ""
        access: "read-write"
        filter: ''
        display: "Access Type"
        comment: ""
      - name: "amfSetId"
        type: "string"
        value: ""
        access: "read-write"
        filter: ''
        display: "AMF Set ID"
        comment: ""
  plmnMappingList:
    display: "PLMN Mapping List"
    array:
      - name: "index"
        type: "int"
        value: "1"
        access: "read-only"
        filter: '1~32'
        display: "Index"
        comment: "1~32"
      - name: "operatorName"
        type: "string"
        value: ""
        access: "read-write"
        filter: ''
        display: "Operator Name"
        comment: ""
      - name: "mcc"
        type: "string"
        value: "001"
        access: "read-write"
        filter: ''
        display: "MCC"
        comment: ""
      - name: "mnc"
        type: "string"
        value: "02"
        access: "read-write"
        filter: ''
        display: "MNC"
        comment: ""
      - name: "servingSnssaiSst"
        type: "int"
        value: "1"
        access: "read-write"
        filter: ''
        display: "Serving SNSSAI SST"
        comment: ""
      - name: "servingSnssaiSd"
        type: "string"
        value: "1"
        access: "read-write"
        filter: ''
        display: "Serving SNSSAI SD"
        comment: ""
      - name: "homeSnssaiSst"
        type: "int"
        value: "1"
        access: "read-write"
        filter: ''
        display: "Home SNSSAI SST"
        comment: ""
      - name: "homeSnssaiSd"
        type: "string"
        value: "1"
        access: "read-write"
        filter: ''
        display: "Home SNSSAI SD"
        comment: ""