smf:
  smfSystem:
    display: "SMF System Config"
    list:
    - name: "sbiIpAddr"
      type: "string"
      value: "172.16.5.150"
      access: "read-write"
      filter: ''
      display: "SBI IP"
      comment: ""
    - name: "sbiPort"
      type: "int"
      value: "8080"
      access: "read-write"
      filter: "0~65535"
      display: "SBI Port"
      comment: "0~65535"
    - name: "sbiScheme"
      type: "enum"
      value: "http"
      access: "read-write"
      filter: "{\"0\":\"http\", \"1\":\"https\"}"
      display: "SBI Scheme"
      comment: ""
    - name: "n4Ipv4"
      type: "ipv4"
      value: "172.16.5.150"
      access: "read-write"
      filter: ''
      display: "N4 IPv4"
      comment: ""
    - name: "n4Ipv6"
      type: "ipv6"
      value: ""
      access: "read-write"
      filter: ''
      display: "N4 IPv6"
      comment: ""
    - name: "n4UIpv4"
      type: "ipv4"
      value: ""
      access: "read-write"
      filter: ''
      display: "N4U IPv4"
      comment: ""
    - name: "n4UIpv6"
      type: "ipv6"
      value: ""
      access: "read-write"
      filter: ''
      display: "N4U IPv6"
      comment: ""
    - name: "amfUri"
      type: "string"
      value: "http://172.16.5.120:8080"
      access: "read-write"
      filter: ''
      display: "AMF URI"
      comment: ""
    - name: "pcfEnable"
      type: "bool"
      value: "true"
      access: "read-write"
      filter: ''
      display: "PCF Enable"
      comment: ""
    - name: "pcfUri"
      type: "string"
      value: "http://172.16.5.160:8080"
      access: "read-write"
      filter: ''
      display: "PCF URI"
      comment: ""
    - name: "udmUri"
      type: "string"
      value: "http://172.16.5.140:8080"
      access: "read-write"
      filter: ''
      display: "UDM URI"
      comment: ""
    - name: "chfEnable"
      type: "bool"
      value: "false"
      access: "read-write"
      filter: "{\"0\":\"false\", \"1\":\"true\"}"
      display: "5G Charging Enable"
    - name: "chfPrimaryUri"
      type: "string"
      value: "http://172.16.5.240:8080"
      access: "read-write"
      filter: ''
      display: "CHF Primary URI"
      comment: "" 
    - name: "chfSecondaryUri"
      type: "string"
      value: ""
      access: "read-write"
      filter: ''
      display: "CHF Secondary URI"
      comment: "" 
    - name: "nrfEnable"
      type: "bool"
      value: "false"
      access: "read-write"
      filter: "{\"0\":\"false\", \"1\":\"true\"}"
      display: "NRF Enable"
      comment: ""      
    - name: "nrfUri"
      type: "string"
      value: "http://172.16.5.180:8080"
      access: "read-write"
      filter: ''
      display: "NRF URI"
      comment: ""      
    - name: "primaryDnsIpv4"
      type: "ipv4"
      value: "114.114.114.114"
      access: "read-write"
      filter: ""
      display: "Primary DNS IPv4"
      comment: ""
    - name: "secondaryDnsIpv4"
      type: "ipv4"
      value: ""
      access: "read-write"
      filter: ""
      display: "Secondary DNS IPv4"
      comment: ""
    - name: "primaryDnsIpv6"
      type: "ipv6"
      value: ""
      access: "read-write"
      filter: ""
      display: "Primary DNS IPv6"
      comment: ""
    - name: "secondaryDnsIpv6"
      type: "ipv6"
      value: ""
      access: "read-write"
      filter: ""
      display: "Secondary DNS IPv6"
      comment: ""
    - name: "primaryPcscfIpv4"
      type: "ipv4"
      value: "172.16.5.110"
      access: "read-write"
      filter: ""
      display: "Primary PCSCF IPv4"
      comment: ""
    - name: "secondaryPcscfIpv4"
      type: "ipv4"
      value: ""
      access: "read-write"
      filter: ""
      display: "Secondary PCSCF IPv4"
      comment: ""
    - name: "primaryPcscfIpv6"
      type: "ipv6"
      value: ""
      access: "read-write"
      filter: ""
      display: "Primary PCSCF IPv6"
      comment: ""
    - name: "secondaryPcscfIpv6"
      type: "ipv6"
      value: ""
      access: "read-write"
      filter: ""
      display: "Secondary PCSCF IPv6"
      comment: ""
    - name: "ueMtu"
      type: "int"
      value: ""
      access: "read-write"
      filter: "0~65535"
      display: "UE MTU"
      comment: ""
  spgwSystem:
    display: "SPGW Sytem Config"
    list:
    - name: "s11Ip"
      type: "string"
      value: "172.16.5.150"
      access: "read-write"
      filter: ''
      display: "Local S11 IP"
      comment: ""
    - name: "localDiameterIp"
      type: "string"
      value: "172.16.5.150"
      access: "read-write"
      filter: ''
      display: "Local Diameter IP"
      comment: ""
    - name: "localDiameterHostName"
      type: "string"
      value: "smf.mnc001.mcc001.3gppnetwork.org"
      access: "read-write"
      filter: ''
      display: "Local Diameter Host Name"
      comment: ""
    - name: "localDiameterRealmName"
      type: "string"
      value: "mnc001.mcc001.3gppnetwork.org"
      access: "read-write"
      filter: ''
      display: "Local Diameter Realm Name"
      comment: ""
    - name: "peerGyEnable"
      type: "bool"
      value: 'false'
      access: "read-write"
      filter: 'false;true;'
      display: "Gy Enable"
      comment: "" 
    - name: "primaryPeerGyIp"
      type: "string"
      value: ""
      access: "read-write"
      filter: ''
      display: "Primary Remote Gy IP"
      comment: ""
    - name: "primaryPeerGyPort"
      type: "int"
      value: "3868"
      access: "read-write"
      filter: "0~65535"
      display: "Primary Remote Gy Port"
      comment: "0~65535"
    - name: "secondaryPeerGyIp"
      type: "string"
      value: ""
      access: "read-write"
      filter: ''
      display: "Secondary Remote Gy IP"
      comment: ""
    - name: "secondaryPeerGyPort"
      type: "int"
      value: "3868"
      access: "read-write"
      filter: "0~65535"
      display: "Secondary Remote Gy Port"
      comment: "0~65535"
    - name: "peerGxEnable"
      type: "bool"
      value: 'false'
      access: "read-write"
      filter: 'false;true;'
      display: "Gx Enable"
      comment: "" 
    - name: "gxChargingEnable"
      type: "bool"
      value: 'false'
      access: "read-write"
      filter: 'false;true;'
      display: "Gx Charging Enable"
      comment: "" 
    - name: "primaryPeerGxIp"
      type: "string"
      value: ""
      access: "read-write"
      filter: ''
      display: "Primary Remote Gx IP"
      comment: ""
    - name: "primaryPeerGxPort"
      type: "int"
      value: "3868"
      access: "read-write"
      filter: "0~65535"
      display: "Primary Remote Gx Port"
      comment: "0~65535"
    - name: "secondaryPeerGxIp"
      type: "string"
      value: ""
      access: "read-write"
      filter: ''
      display: "Secondary Remote Gx IP"
      comment: ""
    - name: "secondaryPeerGxPort"
      type: "int"
      value: "3868"
      access: "read-write"
      filter: "0~65535"
      display: "Secondary Remote Gx Port"
      comment: "0~65535"
  upfConfig:
    display: "UPF Config"
    array:
    - name: "index"
      type: "int"
      value: ""
      access: "read-only"
      filter: '0~2047'
      display: "Index"
      comment: ""
    - name: "id"
      type: "string"
      value: ""
      access: "read-write"
      filter: '1~64'
      display: "UPF ID"
      comment: ""
    - name: "addr"
      type: "string"
      value: ""
      access: "read-write"
      filter: '7~45'
      display: "Address"
      comment: "e.g. ip:port"
    - name: "ipPoolType"
      type:  "string"
      value: "IPv4v6"
      access: "read-write"
      filter: ''
      display: "Ip Pool Type"
      comment: "IPv4,IPv6,IPv4v6"
    - name: "ipv4Pools"
      type:  "string"
      value: ""
      access: "read-write"
      filter: '10~256'
      display: "IPv4 Pools"
      comment: "CIDR format, e.g. 192.168.1.0/24"
    - name: "ipv6Pools"
      type:  "string"
      value: ""
      access: "read-write"
      filter: '5~512'
      display: "IPv6 Pools"
      comment: "CIDR format, e.g. fe80::20c:29ff:fee4:dab7/50"
    - name: "staticIpv4Enable"
      type: "bool"
      value: ""
      access: "read-write"
      filter: "{\"0\":\"false\", \"1\":\"true\"}"
      display: "Static IPv4 Enable"
      comment: ""
    - name: "staticIpv4Start"
      type: "ipv4"
      value: ""
      access: "read-write"
      filter: ''
      display: "Static IPv4 Start"
      comment: "ipv4 format"
    - name: "staticIpv4End"
      type: "ipv4"
      value: ""
      access: "read-write"
      filter: ''
      display: "Static IPv4 End"
      comment: "ipv4 format"
    - name: "staticIpv6Enable"
      type: "bool"
      value: ""
      access: "read-write"
      filter: "{\"0\":\"false\", \"1\":\"true\"}"
      display: "Static IPv6 Enable"
      comment: ""
    - name: "staticIpv6Start"
      type: "ipv6"
      value: ""
      access: "read-write"
      filter: ''
      display: "Static IPv6 Start"
      comment: "ipv6 format"
    - name: "staticIpv6End"
      type: "ipv6"
      value: ""
      access: "read-write"
      filter: ''
      display: "Static IPv6 End"
      comment: "ipv6 format"
    - name: "ueDnnIpPool"
      display: "UE DNN IP Pool"
      array:
      - name: "index"
        type: "int"
        value: ""
        access: "read-only"
        filter: '0~2047'
        display: "Index"
        comment: ""
      - name: "dnn"
        type: "string"
        value: ""
        access: "read-write"
        filter: '1~64'
        display: "DNN"
        comment: ""
      - name: "ipPoolType"
        type:  "string"
        value: "IPv4v6"
        access: "read-write"
        filter: ''
        display: "Ip Pool Type"
        comment: "IPv4,IPv6,IPv4v6"
      - name: "ipv4Pools"
        type:  "string"
        value: ""
        access: "read-write"
        filter: '10~256'
        display: "IPv4 Pools"
        comment: "CIDR format, e.g. 192.168.1.0/24"
      - name: "ipv6Pools"
        type:  "string"
        value: ""
        access: "read-write"
        filter: '5~512'
        display: "IPv6 Pools"
        comment: "CIDR format, e.g. fe80::20c:29ff:fee4:dab7/50"
      - name: "staticIpv4Enable"
        type: "bool"
        value: ""
        access: "read-write"
        filter: "{\"0\":\"false\", \"1\":\"true\"}"
        display: "Static IPv4 Enable"
        comment: ""
      - name: "staticIpv4Start"
        type: "ipv4"
        value: ""
        access: "read-write"
        filter: ''
        display: "Static IPv4 Start"
        comment: "ipv4 format"
      - name: "staticIpv4End"
        type: "ipv4"
        value: ""
        access: "read-write"
        filter: ''
        display: "Static IPv4 End"
        comment: "ipv4 format"
      - name: "staticIpv6Enable"
        type: "bool"
        value: ""
        access: "read-write"
        filter: "{\"0\":\"false\", \"1\":\"true\"}"
        display: "Static IPv6 Enable"
        comment: ""
      - name: "staticIpv6Start"
        type: "ipv6"
        value: ""
        access: "read-write"
        filter: ''
        display: "Static IPv6 Start"
        comment: "ipv6 format"
      - name: "staticIpv6End"
        type: "ipv6"
        value: ""
        access: "read-write"
        filter: ''
        display: "Static IPv6 End"
        comment: "ipv6 format"
  dnnSelectUpf:
    display: "DNN Select UPF"
    array:
    - name: "index"
      type: "int"
      value: "0"
      access: "read-only"
      filter: '0~65535'
      display: "Index"
      comment: ""
    - name: "dnn"
      type: "string"
      value: ""
      access: "read-write"
      filter: '1~64'
      display: "DNN"
      comment: ""
    - name: "upfId"
      type: "string"
      value: ""
      access: "read-write"
      filter: '1~64'
      display: "UPF ID"
      comment: ""
  dnnTaiSelectUpf:
    display: "DNN TAI Select UPF"
    array:
    - name: "index"
      type: "int"
      value: ""
      access: "read-only"
      filter: '0~65535'
      display: "Index"
      comment: ""
    - name: "dnn"
      type: "string"
      value: ""
      access: "read-write"
      filter: '1~64'
      display: "DNN"
      comment: ""
    - name: "tai"
      type: "string"
      value: ""
      access: "read-write"
      filter: '1~64'
      display: "TAI"
      comment: "MCC+MNC+TAC"
    - name: "upfId"
      type: "string"
      value: "upf2-Id"
      access: "read-write"
      filter: '1~64'
      display: "UPF ID"
      comment: ""
  snssaiSelectUpf:
    display: "SNSSAI Select UPF"
    array:
    - name: "index"
      type: "int"
      value: ""
      access: "read-only"
      filter: '0~65535'
      display: "Index"
      comment: ""
    - name: "enable"
      type: "bool"
      value: 'true'
      access: "read-write"
      filter: 'false;true;'
      display: "Enable"
    - name: "snssai"
      type: "string"
      value: "1-000001"
      access: "read-write"
      filter: '1~64'
      display: "SNSSAI"
      comment: "sst1-sd1;sst2-sd2;sst3-sd3"
    - name: "upfId"
      type: "string"
      value: "upf1-Id"
      access: "read-write"
      filter: '1~64'
      display: "UPF ID"
      comment: "upf1-id;upf2-id;upf3-id"
  offlineChargingConfig:
    display: "Offline Charging Config"
    list:
    - name: "cdrFileName"
      type: "string"
      value: "smf.cdr"
      access: "read-write"
      filter: "1~64"
      display: "CDR File Name"
      comment: ""
    - name: "cdrFilePath"
      type: "string"
      value: "/var/log/smfCdr"
      access: "read-write"
      filter: "1~256"
      display: "CDR File Path"
      comment: ""
    - name: "cdrFileNum"
      type: "int"
      value: "50"
      access: "read-write"
      filter: "1~999999999"
      display: "CDR File Num"
      comment: ""
    - name: "cdrFileSize"
      type: "int"
      value: "300"
      access: "read-write"
      filter: "1~999999"
      display: "CDR File Size"
      comment: "Megabytes"
    - name: "cdrFileMaxAge"
      type: "int"
      value: "30"
      access: "read-write"
      filter: "0~9999"
      display: "CDR File Max Age"
      comment: "Days"
    - name: "freeSubsCdrEnable"
      type: "bool"
      value: "false"
      access: "read-write"
      filter: ""
      display: "Free Subscribers CDR Enable"
      comment: ""
    - name: "timeThreshold"
      type: "int"
      value: "600"
      access: "read-write"
      filter: "0~999999999"
      display: "Time Threshold"
      comment: "Seconds"
    - name: "volumeThreshold"
      type: "int"
      value: "0"
      access: "read-write"
      filter: "0~999999999999999"
      display: "Volume Threshold"
      comment: "Bytes"