#!/usr/bin/env python3
"""Generate internal/authz/seeds.go from extracted Java built-in permission lists.

Sources (extracted from nms-serv RoleManagementServiceImpl):
  /tmp/perm_monitor.txt  -> Monitoring role (25 codes)
  /tmp/perm_maintain.txt -> Maintenance role (300 codes)
  /tmp/perm_operator.txt -> operator role (13 codes)
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = {
    "monitor": os.path.join(HERE, "seed_src", "perm_monitor.txt"),
    "maintain": os.path.join(HERE, "seed_src", "perm_maintain.txt"),
    "operator": os.path.join(HERE, "seed_src", "perm_operator.txt"),
}


def load(path):
    out = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            s = line.strip()
            if s:
                out.append(s)
    return out


def emit_var(name, items):
    lines = [f"var {name} = []string{{"]
    for it in items:
        lines.append(f'\t"{it}",')
    lines.append("}")
    return "\n".join(lines)


monitor = load(SRC["monitor"])
maintain = load(SRC["maintain"])
operator = load(SRC["operator"])

# union of all built-in codes (the known permission registry base)
union = []
seen = set()
for it in maintain + monitor + operator:
    if it not in seen:
        seen.add(it)
        union.append(it)

header = """// Code generated by scripts_gen_seeds/gen_seeds.py. DO NOT EDIT.
// Permission ids mirror nms-serv RoleManagementServiceImpl built-in role sets
// (monitorPermissions / maintainPermissions / operatorPermissions).

package authz

// BuiltinMonitorPerms are the permission ids granted to the built-in
// Monitoring role (Java monitorPermissions, 25 codes).
"""

blocks = []
blocks.append(header)
blocks.append(emit_var("BuiltinMonitorPerms", monitor))
blocks.append("")
blocks.append("// BuiltinMaintainPerms are the permission ids granted to the built-in\n// Maintenance role (Java maintainPermissions, 300 codes).")
blocks.append(emit_var("BuiltinMaintainPerms", maintain))
blocks.append("")
blocks.append("// BuiltinOperatorPerms are the permission ids granted to the built-in\n// operator role (Java operatorPermissions, 13 codes). In Java operator is\n// treated as admin (getPermissionIdsForUser sets admin=true).")
blocks.append(emit_var("BuiltinOperatorPerms", operator))
blocks.append("")
blocks.append("// BuiltinRegistryBase is the union of all built-in permission ids. It forms\n// the base of the full permission registry (custom perms from role_has_permission\n// are unioned in at load time).")
blocks.append(emit_var("BuiltinRegistryBase", union))

content = "\n".join(blocks) + "\n"

out_path = os.path.join(os.path.dirname(__file__), "..", "internal", "authz", "seeds.go")
out_path = os.path.abspath(out_path)
with open(out_path, "w", encoding="utf-8") as f:
    f.write(content)

print(f"monitor={len(monitor)} maintain={len(maintain)} operator={len(operator)} union={len(union)}")
print(f"wrote {out_path}")
